### ISSUE TITLE
Repeated API Calls

### ISSUE THREAD

**Issue by enchanteddev** [hemant030406/Weather_Forecasting#37]
When loading the forecast tab, the same API endpoint is being called several times.

![image](https://github.com/user-attachments/assets/2dc018ce-3c9f-4c0d-abc7-1cd22488c8df)

I believe this is happening because of the Fetch function being imported in multiple files, and being called separately. If the response is passed instead of the city name to other UI components, then duplication will be avoided

**Comment by hemant030406** [comment]
fixed
